Repository dzangolab/react, pull requests merged in 2023-02, with the labels that each got.

#140 feat(ui): add stories for tabbedpanel component
  packages/ui/src/components/TabbedPanel/TabbedPanel.stories.tsx
Labels: documentation

#146 feat(ui): add accordion stories
  packages/ui/src/Accordion/Accordion.stories.tsx
  packages/ui/src/TabbedPanel/TabbedPanel.stories.tsx
Labels: documentation

#150 refactor(user): change style of dropdownUserMenu component
  packages/user/src/assets/css/dropdownUserMenu.css
Labels: fix

#156 feat(storybook): restructure storybook
  apps/storybook/.gitignore
  apps/storybook/.storybook/main.js
  apps/storybook/.storybook/preview-head.html
  apps/storybook/.storybook/preview.js
  apps/storybook/package.json
  makefile
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: Storybook

#153 feat(ui): implement storybook on datatable component
  packages/ui/src/Table/BaseTable.css
  packages/ui/src/Table/Table.stories.tsx
  packages/ui/src/Table/TableHeader.tsx
Labels: documentation, Storybook

#162 User/feat redirect login
  apps/demo/src/config.ts
  packages/ui/src/Buttons/LoadingButton/index.tsx
  packages/ui/src/Loading/index.ts
  packages/ui/src/LoadingIcon/__test__/LoadingIcon.snapshot.test.tsx
  packages/ui/src/LoadingIcon/__test__/__snapshots__/LoadingIcon.snapshot.test.tsx.snap
  packages/ui/src/LoadingIcon/index.tsx
  packages/ui/src/LoadingIcon/loadingIcon.css
  packages/ui/src/LoadingPage/index.css
  packages/ui/src/LoadingPage/index.tsx
  packages/ui/src/Page/index.tsx
  packages/ui/src/Page/page.css
  packages/ui/src/index.ts
  packages/user/src/assets/css/redirectMessage.css
  packages/user/src/components/DropdownUserMenu.tsx
  packages/user/src/components/RedirectionMessage.tsx
  packages/user/src/context/UserProvider.tsx
  packages/user/src/index.ts
  packages/user/src/supertokens/login.ts
  packages/user/src/supertokens/logout.ts
  packages/user/src/types/config.ts
  packages/user/src/views/Login.tsx
Labels: enhancement, User
